- name: JavaScript
  logo: javascript
  url: https://github.com/hucki?tab=repositories&q=&type=&language=javascript
  color: F1E05A
  projects:
    - https://github.com/hucki/grouptripper
    - url: https://github.com/hucki/necto
      wip: true
- name: React
  logo: react
  url: https://reactjs.org
  color: 61DAFB
  projects:
    - https://github.com/hucki/grouptripper
    - url: https://github.com/hucki/necto
      wip: true
- name: React-Query
  logo: react
  url: https://github.com/tannerlinsley/react-query
  color: 0769AD
  projects:
    - https://github.com/hucki/grouptripper
- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org
  color: 007ACC
  projects:
    - https://github.com/hucki/grouptripper
- name: Node.js
  logo: nodejs
  url: https://nodejs.org/
  color: 339933
  projects:
    - https://github.com/hucki/grouptripper
    - url: https://github.com/hucki/necto
      wip: true
- name: Express.js
  logo: nodejs
  url: https://expressjs.com
  color: 52C0F2
  projects:
    - https://github.com/hucki/grouptripper
    - url: https://github.com/hucki/necto
      wip: true
- name: MongoDB
  logo: mongodb
  url: https://www.mongodb.com
  color: 47A248
  projects:
    - https://github.com/hucki/grouptripper
